name: Build WebRTC

on:
  schedule:
    # ref: https://help.github.com/en/articles/events-that-trigger-workflows#scheduled-events

    # POSIX cron syntax:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *

    # Operator  Description           Example
    # *         Any value             * * * * *      runs every minute of every day.
    # ,         Value list separator  2,10 4,5 * * * runs at minute 2 and 10 of the 4th and 5th hour of every day.
    # -         Range of values       0 4-6 * * *    runs at minute 0 of the 4th, 5th, and 6th hour.
    # /         Step values           20/15 * * * *  runs every 15 minutes starting from minute 20 through 59 (minutes 20, 35, and 50).

    # cron time generator: https://crontab.guru/

    # * is a special character in YAML so you have to quote this string
    # run every 15mins starting from minute 0 (trough 59) from 12-13h (12:00, 12:15, 12:30, 12:45, 13:00, 13:15, 13:30, 13:45)
    # - cron: '0/15 12-13 * * 1-5'
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    #- uses: .github/workflows/actions/checkout-recursive@master
    - uses: actions/checkout@v1 # https://github.com/actions/checkout
      with:
        submodules: true
        lfs: true
    - name: Set up Python 2.7
      uses: actions/setup-python@v1 # https://github.com/actions/setup-python
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Prepare
      run: |
        cd scripts
        python ./run.py -a prepare -t webrtc -p win --cpus x64 -c debug --noWrapper
    - name: Build
      run: |
        cd scripts
        python ./run.py -a build -t webrtc -p win --cpus x64 -c debug --noWrapper
